#!/bin/bash

if [ $(id -u) != 0 ] ; then
    echo "ERROR: You need sudo."
    exit 1
fi

mount -o bind /var/lib/gh-runner/${SNAP_NAME}/_work ${SNAP}/usr/lib/gh-runner/_work
mount -o bind /var/lib/gh-runner/${SNAP_NAME}/_diag ${SNAP}/usr/lib/gh-runner/_diag
mount -o bind /var/lib/gh-runner/${SNAP_NAME}/.runner ${SNAP}/usr/lib/gh-runner/.runner
mount -o bind /var/lib/gh-runner/${SNAP_NAME}/.credentials ${SNAP}/usr/lib/gh-runner/.credentials
mount -o bind /var/lib/gh-runner/${SNAP_NAME}/.credentials_rsaparams ${SNAP}/usr/lib/gh-runner/.credentials_rsaparams
mount -o bind /var/lib/gh-runner/${SNAP_NAME}/svc.sh ${SNAP}/usr/lib/gh-runner/svc.sh

cd ${SNAP}/usr/lib/runner

sudo -u $SUDO_USER ./config.sh

umount /var/lib/gh-runner/${SNAP_NAME}/_work
umount /var/lib/gh-runner/${SNAP_NAME}/_diag
umount /var/lib/gh-runner/${SNAP_NAME}/.runner
umount /var/lib/gh-runner/${SNAP_NAME}/.credentials
umount /var/lib/gh-runner/${SNAP_NAME}/.credentials_rsaparams
umount /var/lib/gh-runner/${SNAP_NAME}/svc.sh
