name: runner
# title:
type: app
base: core20
version: git
summary: The Runner for GitHub Actions
description: |
  The snap version of `Runner for GitHub Actions`
build-base: core18

grade: stable
confinement: strict

environment:
  SHELL: bash
  # LANG: null
  LC_ALL: C



parts:
  runner:
    source: https://github.com/actions/runner.git
    source-tag: v2.165.2
    plugin: nil
    override-build: |
      cd ./src/
      ./dev.sh
      snapcraftctl build
    build-packages:
      - zlib1g-dev
      - liblttng-ust0
      - libkrb5-3
      - zlib1g
      - libssl1.1
      - libicu-dev
      - libicu60
    #stage-packages:
      #- libicu63
    
