name: runner
# title:
type: app
base: core20
version: v2.165.2
summary: The Runner for GitHub Actions
description: |
  The snap version of `Runner for GitHub Actions`
build-base: core18

grade: stable
confinement: strict

environment:
  SHELL: bash
  # LANG: null
  LC_ALL: C

apps:
  runner: 
    command: run.sh

parts:
  runner:
    source: https://github.com/actions/runner.git
    source-tag: v2.165.2
    plugin: nil
    override-build: |
      set -ex
      cd ./src/
      ./dev.sh build
      ./dev.sh runtest
      ./dev.sh layout
      ./dev.sh package
      tar xzf ${SNAPCRAFT_PART_BUILD}/_package/actions-runner-linux-x64-2.165.0.tar.gz
      snapcraftctl build
    build-packages:
      - zlib1g-dev
      - liblttng-ust0
      - libkrb5-3
      - zlib1g
      - libssl1.1
      - libicu-dev
      - libicu60
    #stage-packages:
      #- libicu63
    stage:
      - -./LICENSE
      - -./README.md
      - -./_dotnetsdk
      - -./_downloads
      - -./_layout
      - -./docs
      - -./releaseNote.md
      - -./releaseVersion
      - -./src
    
