name: runner
# title:
type: app
base: core20
version: v2.165.2
summary: The Runner for GitHub Actions
description: |
  The snap version of `Runner for GitHub Actions`
build-base: core18

grade: stable
confinement: classic

environment:
  SHELL: bash
  # LANG: null
  LC_ALL: C

  LD_LIBRARY_PATH: $SNAP/usr/lib/runner:$LD_LIBRARY_PATH

apps:
  gh-runner: 
    command: usr/lib/runner/run.sh
  gh-config:
    command: usr/lib/runner/config.sh

hooks:
  install:
    plugs:
      - mount-observe  # to read /proc/*/mounts
      - network  # to connect to the db for running upgrades
  post-refresh:
    plugs:
      - mount-observe  # to read /proc/*/mounts
      - network  # to connect to the db for running upgrades

layout:
  /var/lib/runner/_work:
    bind: $SNAP/usr/lib/runner/_work
  /var/lib/runner/_diag:
    bind: $SNAP/usr/lib/runner/_diag
  /var/lib/runner/.runner:
    bind-file: $SNAP/usr/lib/runner/.runner
  /var/lib/runner/.credentials_rsaparams:
    bind-file: $SNAP/usr/lib/runner/.credentials_rsaparams
  /var/lib/runner/.credentials:
    bind-file: $SNAP/usr/lib/runner/.credentials
  /var/lib/runner/svc.sh:
    bind-file: $SNAP/usr/lib/runner/svc.sh

parts:
  externals:
     plugin: dump
     source: .
     organize:
       env: .env
       path: .path

  runner:
    source: https://github.com/actions/runner.git
    source-tag: v2.165.2
    plugin: dump
    override-build: |
      set -ex
      cd ${SNAPCRAFT_PART_BUILD}/src/
      ./dev.sh build
      ./dev.sh runtest
      ./dev.sh layout
      ./dev.sh package
      snapcraftctl build
    override-stage: |
      set -ex
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/usr/lib/runner
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/var/lib/runner/_work
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/var/lib/runner/_diag
      touch ${SNAPCRAFT_PART_INSTALL}/var/lib/runner/.runner
      touch ${SNAPCRAFT_PART_INSTALL}/var/lib/runner/.credentials
      touch ${SNAPCRAFT_PART_INSTALL}/var/lib/runner/.credentials_rsaparams
      touch ${SNAPCRAFT_PART_INSTALL}/var/lib/runner/svc.sh
      cd ${SNAPCRAFT_PART_INSTALL}/usr/lib/runner
      tar xzf "${SNAPCRAFT_PART_BUILD}/_package/actions-runner-linux-x64-2.165.0.tar.gz"
      snapcraftctl stage
    build-packages:
      - zlib1g-dev
      - liblttng-ust0
      - libkrb5-3
      - zlib1g
      - libssl1.1
      - libicu-dev
      - libicu60
    #stage-packages:
      #- libicu63
    stage:
      - usr/
      - var/
    
