#!/bin/bash -e


mkdir -p /var/lib/runner/${SNAP_NAME}/_work
mkdir -p /var/lib/runner/${SNAP_NAME}/_diag
touch /var/lib/runner/${SNAP_NAME}/.runner
touch /var/lib/runner/${SNAP_NAME}/.credentials
touch /var/lib/runner/${SNAP_NAME}/.credentials_rsaparams
touch /var/lib/runner/${SNAP_NAME}/svc.sh


